repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt --all --check
        entry: cargo fmt --all --check
        language: system
        pass_filenames: false
        files: '\.rs$'
